eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      path: /**
      serviceId: registration-service

server:
  port: 8081