eureka:
  client:
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      path: /**
      serviceId: registration-service

ribbon:
  ServerListRefreshInterval: 5000

server:
  port: 8081