spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:skbdb
    username: sa
    password: password
  h2:
    console:
      enabled: true

  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672
    producer: registration->resolver

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka

server:
  port: 8082
